version: 2
updates:
  - package-ecosystem: docker
    directory: /alpine-amd64/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-armhf/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-aarch64/
    schedule:
      interval: weekly